[phases.setup]
commands = [
  "apt-get update && apt-get install -y unzip curl",
  "curl -fsSL https://bun.sh/install | bash",
  "echo 'export PATH=$HOME/.bun/bin:$PATH' >> /etc/profile",
  
  "source /etc/profile && bun install",
]

[phases.build]
commands = [
  "source /etc/profile && bun build"
]

[phases.start]
commands = ["source /etc/profile && bun run start"]

[environment]
PATH = "$HOME/.bun/bin:$PATH"
