[phases.setup]
pkgs  = ["nodejs", "bun"]
cmds = ["bun --version"]
providers = ["bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"

[variables]
NODE_PACKAGE_MANAGER = "bun"