[phases.setup]
commands = [
    "npm install -g bun"
]
nixPkgs = ["bun"]

[phases.install]
commands = [
    "bun install"
]

[phases.build]
commands = [
    "bun run build"
]

[start]
cmd = "bun run start"
