[phases.setup]
pkgs = ["bun"]
cmds = ["bun --version"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"

[variables]
NODE_PACKAGE_MANAGER = "bun"
NIXPACKS_NO_INSTALL_NODE = "1"
NIXPACKS_PKGS = "bun"