
[phases.setup]
commands = [
    "npm install -g bun"
]

[phases.install]
commands = [
    "bun install"
]

[phases.build]
commands = [
    "bun run build"
]

[phases.start]
commands = ["bun run start"]
